### ISSUE TITLE
Nullable int 32 is always unmarshalled with `isSet = true`

### ISSUE THREAD

**Issue by kramen22** [plaid/plaid-go#271] opened 2023-06-08 18:21 UTC
https://github.com/plaid/plaid-go/blob/9d8416b7c9793f4e780a72e92b2fee179abd412b/plaid/utils.go#L146

I came across this issue when trying to use the IsSet function on the `ExpiredAt` field in a JWK returned from a `WebhookVerificationKeyGet` call in the following struct: https://github.com/plaid/plaid-go/blob/9d8416b7c9793f4e780a72e92b2fee179abd412b/plaid/model_jwk_public_key.go#L36 

Even though the `ExpiredAt` field is not in the json returned from the api call, the `isSet` value is always true.

Possible fix: check that `len(src) > 0` before setting isSet to true in the `UnmarshallJSON` function for NullableInt32's, or add omitempty to the json tag in the JWK struct.

**Comment by phoenixy1** [comment] 2023-06-08 20:29
the root cause of this behavior is that the API behavior doesn't match the API spec used to generate the client library -- the spec states that `expired_at` has to be in the json returned from the API call. I'll flag this to the team and see how they want to handle it.

**Comment by phoenixy1** [comment] 2023-06-12 23:57
@kramen22 hi, just a clarifying question to help me troubleshoot -- are you seeing a JSON object being returned with `expired_at: null` (which is the correct behavior) or are you seeing a JSON object with no `expired_at` field at all (incorrect behavior)? From your question it sounds like you were seeing no `expired_at` field at all, but I was unable to reproduce that when I tried making calls with Postman.

If you're having issues with unmarshalling and `expired_at` is not in the JSON object, that's a problem with our API not matching the spec, but if you're having issues with unmarshalling and `expired_at` is `null` (rather than totally absent from the JSON object) I think this might be a bug in the OpenAPI generator tool suite we're using to generate the client libraries.

**Comment by phoenixy1** [comment] 2023-06-14 00:02
Looks like the fix was only scoped to strings. I have a PR in progress that is just awaiting approval and then should go out with the next go client library release.

**Comment by phoenixy1** [comment] 2023-06-21 21:12
this should now be fixed in the client library release that went out earlier this week. please comment or open an new issue if you're still experiencing any problems after upgrading to it.

**Closed by phoenixy1** 2023-06-21 21:12 UTC
